### ISSUE TITLE
Please mention 32bit .net runtime is needed in readme file.

### ISSUE THREAD

**Issue by arun54321** [franzageek/WinEFIMounter#2]
I installed x64 .NET and it didn't work.

**Comment by franzageek** [comment]
Alright, will look forward to updating the README file and mentioning that.

**Comment by 1dolla** [comment]
Also, when running the .exe manually from a command prompt, there's actually a response here telling me that I need this .NET package, and a working link to  a setup package for it. Perhaps this could be shown instead of the program just exiting without any feedback? I'm guessing a lot of people give up at this point :)

**Comment by franzageek** [comment]
thats what i mean when i refer to C# as a "crappy choice" - im sorry everyone, will get to move everything to C++ asap.

**Comment by franzageek** [comment]
i've just uploaded an update, please let me know if you experience any weird behavior or if everything works as expected. take care y'all!
